export const KANA_STATUS = {
  a_hiragana: { highlight: true, unlock: true },
  ka_hiragana: { highlight: false, unlock: false },
  sa_hiragana: { highlight: false, unlock: false },
  ta_hiragana: { highlight: false, unlock: false },
  na_hiragana: { highlight: false, unlock: false },
  ha_hiragana: { highlight: false, unlock: false },
  ma_hiragana: { highlight: false, unlock: false },
  ya_hiragana: { highlight: false, unlock: false },
  ra_hiragana: { highlight: false, unlock: false },
  wa_hiragana: { highlight: false, unlock: false },

  ga_hiragana: { highlight: false, unlock: false },
  za_hiragana: { highlight: false, unlock: false },
  da_hiragana: { highlight: false, unlock: false },
  ba_hiragana: { highlight: false, unlock: false },
  pa_hiragana: { highlight: false, unlock: false },

  a_katakana: { highlight: false, unlock: false },
  ka_katakana: { highlight: false, unlock: false },
  sa_katakana: { highlight: false, unlock: false },
  ta_katakana: { highlight: false, unlock: false },
  na_katakana: { highlight: false, unlock: false },
  ha_katakana: { highlight: false, unlock: false },
  ma_katakana: { highlight: false, unlock: false },
  ya_katakana: { highlight: false, unlock: false },
  ra_katakana: { highlight: false, unlock: false },
  wa_katakana: { highlight: false, unlock: false },

  ga_katakana: { highlight: false, unlock: false },
  za_katakana: { highlight: false, unlock: false },
  da_katakana: { highlight: false, unlock: false },
  ba_katakana: { highlight: false, unlock: false },
  pa_katakana: { highlight: false, unlock: false },
};
