export const KANA_STATUS = {
  a_hiragana: { highlight: true, unlock: true },
  ka_hiragana: { highlight: false, unlock: false },
  sa_hiragana: { highlight: false, unlock: false },
  ta_hiragana: { highlight: false, unlock: false },
  na_hiragana: { highlight: false, unlock: false },
  ha_hiragana: { highlight: false, unlock: false },
  ma_hiragana: { highlight: false, unlock: false },
  ya_hiragana: { highlight: false, unlock: false },
  ra_hiragana: { highlight: false, unlock: false },
  wa_hiragana: { highlight: false, unlock: false },

  ga_hiragana: { highlight: false, unlock: false },
  za_hiragana: { highlight: false, unlock: false },
  da_hiragana: { highlight: false, unlock: false },
  ba_hiragana: { highlight: false, unlock: false },
  pa_hiragana: { highlight: false, unlock: false },

  a_katakana: { highlight: false, unlock: false },
  ka_katakana: { highlight: false, unlock: false },
  sa_katakana: { highlight: false, unlock: false },
  ta_katakana: { highlight: false, unlock: false },
  na_katakana: { highlight: false, unlock: false },
  ha_katakana: { highlight: false, unlock: false },
  ma_katakana: { highlight: false, unlock: false },
  ya_katakana: { highlight: false, unlock: false },
  ra_katakana: { highlight: false, unlock: false },
  wa_katakana: { highlight: false, unlock: false },

  ga_katakana: { highlight: false, unlock: false },
  za_katakana: { highlight: false, unlock: false },
  da_katakana: { highlight: false, unlock: false },
  ba_katakana: { highlight: false, unlock: false },
  pa_katakana: { highlight: false, unlock: false },
};

export const HIRAGANA_ORDER = [
  "a_hiragana",
  "ka_hiragana",
  "ga_hiragana",
  "sa_hiragana",
  "za_hiragana",
  "ta_hiragana",
  "da_hiragana",
  "na_hiragana",
  "ha_hiragana",
  "ba_hiragana",
  "pa_hiragana",
  "ma_hiragana",
  "ya_hiragana",
  "ra_hiragana",
  "wa_hiragana",
];
export const KATAKANA_ORDER = [
  "a_katakana",
  "ka_katakana",
  "ga_katakana",
  "sa_katakana",
  "za_katakana",
  "ta_katakana",
  "da_katakana",
  "na_katakana",
  "ha_katakana",
  "ba_katakana",
  "pa_katakana",
  "ma_katakana",
  "ya_katakana",
  "ra_katakana",
  "wa_katakana",
];
